const PortfolioData = [
  {
    id: 1,
    category: 'Web site',
    tech: 'Ruby on Rails | JavaScript | React | Redux',
    title: 'Dream Rent',
    image: 'https://raw.githubusercontent.com/Shubh-Dev/portfolio-shubh/src/assets/images/project-screenshoot/dream-rent-2.png',
    description: 'Dream Rent is a web application that allows users to book an appointment with the house owner',
    seelive: 'https://dream-rent-booking.netlify.app/',
    seesource: 'https://github.com/Shubh-Dev/dream-rent.git',
  },
  {
    id: 2,
    category: 'Web app',
    tech: 'React | redux | CSS',
    title: 'Corona Tracker',
    image: 'https://raw.githubusercontent.com/Shubh-Dev/portfolio-shubh/src/assets/images/project-screenshoot/corona-tracker.png',
    description: 'Corona Tracker is a web application that allows users to track the number of cases of COVID-19',
    seelive: 'https://cheery-concha-41a565.netlify.app/',
    seesource: 'https://github.com/Shubh-Dev/corona-info-tracker.git',
  },
  {
    id: 3,
    category: 'Web site',
    tech: 'React | JavaScript | CSS',
    title: 'Math Magicians',
    image: 'https://raw.githubusercontent.com/Shubh-Dev/portfolio-shubh/src/assets/images/project-screenshoot/math-magician.png',
    description: 'Math Magicians is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: Make simple calculations, Read a random math-related quote.',
    seelive: 'https://sage-nasturtium-ac5b73.netlify.app/',
    seesource: 'https://github.com/Shubh-Dev/react-math-magician-shubh.git',
  },
  {
    id: 4,
    category: 'web site',
    tech: 'React | Redux | CSS',
    title: 'Space Travelers',
    image: 'https://raw.githubusercontent.com/Shubh-Dev/portfolio-shubh/src/assets/images/project-screenshoot/space-travelers.png',
    description: 'Space Travelers is a web application that allows users to book rockets and join selected space missions.',
    seelive: 'https://travelers-hub-rich-shubh.netlify.app/',
    seesource: 'https://github.com/assadounto/space-x.git',
  },
];
export default PortfolioData;
